### ISSUE TITLE
mysql config

### ISSUE THREAD

**Issue by pjv** [521dimensions/ansible-postal#2]
Hi again @jaydrogers,

i was just doing some performance tuning on my postal server in preparation for doing a relatively large-ish mass newsletter mailing (~32K mails). It worked surprisingly well.

In the course of tweaking the settings for the server, i discovered that the mysql config that ansible-postal places at `/etc/mysql/mariadb.conf.d/postal.cnf` seems to be non-functional.

by default It's trying to configure the `innodb_buffer_pool_size` to be 256M, but on my running system, that value was 128M (determined by querying that variable in mysql). I also tried putting some other values into `/etc/mysql/mariadb.conf.d/postal.cnf` and they were ignored on restart of mariadb.

in order to make the changes i was trying to make, i had to edit `/etc/mysql/my.cnf`.

the server was a fresh install of 18.04 with no modifications made to mariadb / mysql other than running the ansible-postal playbook.

**Comment by jaydrogers** [comment]
Thanks for pointing this out! I thought when I tested this it worked, but I will give it another try and see if I need to make modifications.

**Comment by pjv** [comment]
it looks like it *should* work. But the mysql / mariadb config files on debian / ubuntu are so convoluted that it's very hard to tell what the hell matters and what doesn't.

**Comment by jaydrogers** [comment]
Hahahaha I agree. I haven't had a chance to dive deep into this yet, but I did find some resources in my notes that may or may not help you.

It was highly related and I just wanted to share incase it was anything of value. You can view a HTML version of my notes below:

[InnoDBNotes.zip](https://github.com/521dimensions/ansible-postal/files/3467948/InnoDBNotes.zip)
