### ISSUE TITLE
Obtain LE Certs Tasks Failing (Timeout errors)

### ISSUE THREAD

**Issue by ilovepancakes95** [521dimensions/ansible-postal#6]
The playbook is failing for me on the Obtain Let's Encrypt Certificate task. It mentions a timeout and it is likely a firewall issue to reference /opt/postal/.acme.sh/acme.sh.log for more info. See below link with my output of that log. I thought maybe it had to do with Port 80 not being open on Vultr but I added a Port 80 allow rule to my firewall on Vultr for the VM and still no dice. So for some reason, LE can't seem to verify for the cert because it can't access the verification file on the VM via port 80. This is my guess, but open to any input and how this can be fixed.

https://pastebin.com/wLxQm0Ut

**Comment by ilovepancakes95** [comment]
Disregard the above. I setup a new Ubuntu 18.04 VM to just try everything from scratch and it worked. Not sure what was wrong with other VM, but something was messing up comms on port 80 I guess. UFW and Vultr both were allowing 80 so I'm not sure what it was.

**Comment by jaydrogers** [comment]
Thanks for the follow up! No sweat about it. Stuff like this happens to me all of the time 🤣

Glad you were able to get this resolved!
